페이지 UI: 즐겨찾기 페이지
Kernel360/F1-WashPedia-FE pull request #124
Opened 2024-01-23 09:35 UTC by seoye0ng

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] TEST : 테스트 추가 및 리팩토링
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes

1. 즐겨찾기 페이지 UI 제작
2. useScroll 커스텀 훅 제작
3. scroll 시 애니메이션 구현

### How it Works

### To Reviewers

2024-01-24 02:13 UTC, wookki requested changes
고생하셨습니다!

2024-01-24 02:13 UTC, wookki commented on src/app/favorite/page.tsx
> +      <Spacing size={8} />
피그마에선 12px로 되어있네요 채은님께 말씀드려 통일시켜보죠!

2024-01-24 02:13 UTC, wookki commented on src/app/favorite/page.module.scss
> +    .productArticleContainer {
무한 스크롤로 인해 productArticle이 엄청 쌓이게 되면 애니메이션 효과가 버벅임 없이 동작하는지 한번 봐야할 것 같아요!

2024-01-25 03:05 UTC, seoye0ng commented on src/app/favorite/page.module.scss
> +    .productArticleContainer {
넵!

2024-01-25 03:06 UTC, seoye0ng commented on src/app/favorite/page.tsx
> +      <Spacing size={8} />
넵 일단 12로 수정했습니다!

2024-01-25 03:07 UTC, seoye0ng commented on src/hooks/useScroll.ts
> +    window.addEventListener('scroll', handleScroll);
이거 라이브러리 불러오려다가 git rebase했더니.. 이전 커밋 로그까지 같이 찍혀버렸네요...흑흑... throttle 적용했습니다!

2024-01-25 03:07 UTC, seoye0ng commented on src/app/favorite/page.tsx
> +import useScroll from '@/hooks/useScroll';
수정완료했습니다!

2024-01-25 03:07 UTC, bottlewook approved these changes
고생하셨습니다~!

2024-01-25 03:17 UTC, merged