공통 컴포넌트: Common component header
Kernel360/F1-WashPedia-FE pull request #35
Opened 2024-01-05 04:59 UTC by seoye0ng

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [x] TEST : 테스트 추가 및 리팩토링
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

### Key Changes

1. Header 아이콘 컴포넌트 제작
2. Header 컴포넌트 레이아웃 구현
3. 하트 아이콘 클릭시 색상변경 구현
4. 로그인 클릭시 로그인 페이지로 이동
5. Header 스토리북 제작
 
### How it Works

### To Reviewers

2024-01-05 05:18 UTC, wookki commented on src/components/shared/header/Header.module.scss
> +        a {
이거 global css에 적용 되어있어서 빼도 되지 않나요?

2024-01-05 05:18 UTC, wookki commented on src/components/shared/header/Header.tsx
> +import React from 'react';
```suggestion
```
지워주세요~

2024-01-05 06:19 UTC, wookki requested changes
고생하셨습니다!!

2024-01-05 06:19 UTC, wookki commented on src/components/shared/header/headerItems/CenterIcon.tsx
> +import React from 'react';
```suggestion

```

2024-01-05 06:19 UTC, wookki commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +import React from 'react';
```suggestion
```

2024-01-05 06:19 UTC, wookki commented on src/components/shared/header/Header.module.scss
> +    background-color: var(--white);
이거 sass 지원하는 변수 형태인 $white로 사용할 수 있도록 설정을 바꿔볼까요?

2024-01-05 10:12 UTC, wookki commented on src/components/shared/header/types/headerType.tsx
> +interface CommonProps {
확장자 tsx -> ts로 변경해주세요

2024-01-06 11:44 UTC, seoye0ng commented on src/components/shared/header/headerItems/CenterIcon.tsx
> +function CenterIcon({ className }:CenterIconProps) {
수정완료!

2024-01-06 11:44 UTC, seoye0ng commented on src/components/shared/header/Header.module.scss
> +    background-color: var(--white);
수정완료!

2024-01-06 11:44 UTC, seoye0ng commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +import React from 'react';
수정완료!

2024-01-06 11:44 UTC, seoye0ng commented on src/components/shared/header/headerItems/CenterIcon.tsx
> +import React from 'react';
수정완료!

2024-01-06 11:44 UTC, seoye0ng commented on src/components/shared/header/Header.module.scss
> +        margin: 0;
수정완료!

2024-01-06 11:45 UTC, seoye0ng commented on src/components/shared/header/Header.module.scss
> +        list-style: none;
수정 완료!

2024-01-06 11:45 UTC, seoye0ng commented on src/components/shared/header/Header.tsx
> +          className={styles.right}
수정 완료!

2024-01-06 11:45 UTC, seoye0ng commented on src/components/shared/header/Header.tsx
> +      <ul className={styles.container}>
수정 완료!

2024-01-06 11:45 UTC, seoye0ng commented on src/components/shared/header/Header.tsx
> +    <nav className={`${styles.nav} ${isTransparent ? styles.transparent : ''}`}>
수정 완료!

2024-01-06 11:45 UTC, seoye0ng commented on src/components/shared/header/Header.tsx
> +import React from 'react';
수정 완료!

2024-01-06 12:28 UTC, seoye0ng commented on src/components/shared/header/headerItems/RightIcon.tsx
> +import Share from '@/components/icons/Share';
수정완료

2024-01-06 12:28 UTC, seoye0ng commented on src/components/shared/header/headerItems/RightIcon.tsx
> +import Heart from '@/components/icons/Heart';
수정완료

2024-01-06 12:29 UTC, seoye0ng commented on src/components/shared/header/headerItems/RightIcon.tsx
> +import Share from '@/components/icons/Share';
수정완료

2024-01-06 12:29 UTC, seoye0ng commented on src/components/shared/header/headerItems/RightIcon.tsx
> +    setIsClicked(!isClicked);
수정완료

2024-01-06 12:29 UTC, seoye0ng commented on src/components/shared/header/types/headerType.tsx
> +interface CommonProps {
수정완료

2024-01-06 12:29 UTC, seoye0ng commented on src/components/shared/header/headerItems/CenterIcon.tsx
> +import Logo from '@/components/icons/Logo';
수정완료

2024-01-06 12:30 UTC, wookki approved these changes
고생했어요~~!

2024-01-06 12:31 UTC, seoye0ng commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +import BackArrow from '@/components/icons/BackArrow';
수정완료

2024-01-06 12:31 UTC, merged