공통 컴포넌트: Header UI 변경
Kernel360/F1-WashPedia-FE pull request #84
Opened 2024-01-16 10:07 UTC by seoye0ng

## 해당 사항 (중복 선택)

- [x] FEAT : 새로운 기능 추가 및 개선
- [ ] TEST : 테스트 추가 및 리팩토링
- [ ] FIX : 버그 수정
- [ ] REFACTOR : 결과의 변경 없이 코드의 구조를 재조정
- [ ] STYLE : 코드 스타일에 관련된 변경 사항
- [ ] DOCS : 코드가 아닌 문서를 수정한 경우
- [ ] REMOVE : 파일을 삭제하는 작업만 수행
- [ ] RENAME : 파일 또는 폴더명을 수정하거나 위치(경로)를 변경
- [ ] CHORE : 패키지 매니저 설정, 코드 수정 없이 설정 변경(eslint) 등 기타 사항

## 설명

1. 메인페이지 Header UI 수정
2. icon 변경 및 추가
3. storybook 수정

### Key Changes

### How it Works

### To Reviewers

2024-01-16 17:29 UTC, wookki requested changes
고생하셨습니다!!
헤더가 많이 바뀌고 있네요ㅠ🫠

2024-01-16 17:29 UTC, wookki commented on public/assets/icons/filldheart.svg
파일명 filledHeart로 바꿔주세요!

2024-01-16 17:29 UTC, wookki commented on src/components/icons/FilldHeart.tsx
파일명 FilledHeart로 바꿔주세요~

2024-01-16 17:29 UTC, wookki commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +        <Text>홈</Text>
즐겨찾기 페이지에서 사용될 즐겨찾기 문구도 추가해야할 것 같아요!

2024-01-16 17:58 UTC, wookki commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +        <Text>홈</Text>
마이프로필 페이지에서도 문구가 계속 바뀌네요.. props로 바꿔야할 것 같아요!🫠
<img width="195" alt="스크린샷 2024-01-17 오전 2 56 42" src="https://github.com/Kernel360/F1-WashPedia-FE/assets/103362820/bdadb4d2-bf43-441d-9dd3-861d2ded8592">

2024-01-17 11:36 UTC, seoye0ng commented on src/components/shared/header/headerItems/LeftIcon.tsx
> +        <Text>홈</Text>
오오 이부분 수정하겠습니다!

2024-01-18 08:55 UTC, wookki approved these changes
고생하셨습니다!!

2024-01-18 08:56 UTC, merged